cache:
  paths:
    - venv/

before_script:
  - python3 -V
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip virtualenv
  - pip install --upgrade pytest
  - pip install --upgrade pylint
  - pip install --upgrade build
  - pip install -r requirements.txt

run_tests:
  script:
    - pytest
  stage: test

run_lint:
  script:
    - pylint yajl
  stage: test

build_wheel:
  stage: build
  script:
    - python -m build
  artifacts:
    paths:
      - dist/*
    expire_in: 3 days
  only:
     - main
