os: linux
language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - nightly
install:
  - pip install --upgrade pip virtualenv || pip install --user --upgrade pip virtualenv  # Travis...
  - pip install -r requirements.txt
  - pip install build
script:
  - pytest tests
  - pylint yajl
  - python -m build

jobs:
  include:
    - name: 'Python: 3.7'
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.7.9
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:/c/tools/bin:$PATH**
    - name: 'Python: 3.8'
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.8.8
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:/c/tools/bin:$PATH**
    - name: 'Python: 3.9'
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.9.2
      env:
        - PATH=/c/Python39:/c/Python39/Scripts:/c/tools/bin:$PATH**
    - name: 'Python: nightly'
      language: shell
      os: windows
      before_install:
        - choco install python --pre
      env:
        - PATH=/c/Python310:/c/Python310/Scripts:/c/tools/bin:$PATH**
